SQUASHME: zuf: fix userspace include of statfs
The correct header for statfs64 is <sys/statfs.h> (see 'man statfs').

We were using a coincidence where <asm/statfs.h> worked fine if we
didn't include any conflicting headers.

Now, we tried to include "zus_api.h" in xfs_io in order to use the
snapshots API and got compilation errors:
 /usr/include/asm-generic/statfs.h:46:8: error: redefinition of ‘struct statfs64’
This is because <xfs.h> includes <sys/statfs.h> and it conflict with
<asm/statfs.h>.
We can't force users to change their canonical headers so lets be more
conforming.

The solution is to split the include to Kernel and user-space.
After the split, we can call the proper header in kernel too -
<linux/statfs.h>.

Of course, things are not that easy and we must turn on
__USE_LARGEFILE64, otherwise statfs.h won't add 'struct statfs64'.

Signed-off-by: Yigal Korman <yigalk@netapp.com>
Reviewed-by: Boaz Harrosh <boaz.harrosh@netapp.com>